version: "1"
build:
    args:
        - PROJECTROOT
        - TOOLBIN
    variables:
        - TOOLCHAIN="$(TOOLBIN)/arm-none-eabi-"
        - OBJFOLDER="$(PROJECTROOT)/obj"
        - BUILDFOLDER="$(PROJECTROOT)/build"
        - OPT=-Os
        - LINK_SCRIPT="$(PROJECTROOT)/f1c100s/f1c100s_dram.ld"
        - DRAM_SIZE=64M
        - LIBS:
            - "-lgcc"
            - "-lm"
            - "-lc_nano"
        - INCLUDES:
            - "-I$(PROJECTROOT)/f1c100s/arm926/inc"
            - "-I$(PROJECTROOT)/f1c100s/drivers/inc"
            - "-I$(PROJECTROOT)/lib/printf"
            - "-I$(PROJECTROOT)/src"
        - DEFS:
            - "-D__ARM32_ARCH__=5"
            - "-D__ARM926EJS__"
            - "-DPRINTF_ALIAS_STANDARD_FUNCTION_NAMES=1"
            - "-DPRINTF_ALIAS_STANDARD_FUNCTION_NAMES_HARD=1"
        - COMPILE_FLAGS:
            - "-march=armv5te"
            - "-mtune=arm926ej-s"
            - "-mfloat-abi=soft"
            - "-marm"
            - "-mno-thumb-interwork"
            - "-g"
            - "-ggdb"
            - "-Wall"
            - "-fdata-sections"
            - "-ffunction-sections"
            - "-ffreestanding"
            - "-std=gnu99"
        - ASFLAGS:
            - "$(COMPILE_FLAGS)"
            - "$(DEFS)"
        - CFLAGS:
            - "$(COMPILE_FLAGS)"
            - "$(OPT)"
            - "-fomit-frame-pointer"
            - "-Wall"
            - "-fverbose-asm"
            - "$(DEFS)"
        - LDFLAGS:
            - "-nostartfiles"
            - "-Xlinker" 
            - "--gc-sections" 
            - "-T$(LINK_SCRIPT)"
            - "-Wl,--defsym=DRAM_SIZE=$(DRAM_SIZE),-Map=$(BUILDFOLDER)/build.map,--cref,--no-warn-mismatch"
        - OBJS=$[$(OBJFOLDER)/*.obj]
    tools:
        - CC: $(TOOLCHAIN)gcc.exe
        - CP: $(TOOLCHAIN)objcopy.exe
        - SZ: $(TOOLCHAIN)size.exe
        - AS:
            bin: $(TOOLCHAIN)gcc.exe
            args: -x assembler-with-cpp
    targets:
        build:
            steps:
                - name: "Build assembly"
                  tool: CC
                  args: "-c $(ASFLAGS) $(INCLUDES) ${IN} -o ${OUT}"
                  in:
                    - "$(PROJECTROOT)/f1c100s/arm926/src/image.S"
                    - "$(PROJECTROOT)/f1c100s/arm926/src/vectors.S"
                    - "$(PROJECTROOT)/f1c100s/arm926/src/cache-v5.S"
                  out: $(OBJFOLDER)
                - name: "Build C"
                  tool: CC
                  args: "-c $(CFLAGS) $(INCLUDES) ${IN} -o ${OUT}"
                  in:
                    - "$(PROJECTROOT)/f1c100s/drivers/src/*.c"
                    - "$(PROJECTROOT)/lib/printf/printf.c"
                    - "$(PROJECTROOT)/lib/syscalls/syscalls.c"
                    - "$(PROJECTROOT)/src/*.c"
                  out: $(OBJFOLDER)
                - name: "Link ELF"
                  tool: CC
                  args: "$(LDFLAGS) -o ${OUT} $(OBJS) $(LIBS)"
                  out: $(BUILDFOLDER)/build.elf
                - name: "Build binary"
                  tool: CP
                  args: "-O binary $(BUILDFOLDER)/build.elf ${OUT}"
                  out: $(BUILDFOLDER)/usb-boot.bin
                - name: "Size"
                  tool: SZ
                  args: "${IN}"
                  in: $(BUILDFOLDER)/build.elf
